language: ruby
os:
  - linux
  - osx
rvm: # http://rubies.travis-ci.org/
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
matrix:
  exclude:
    - os: osx
      rvm: 1.9
    - os: osx
      rvm: 2.0
    - os: osx
      env: WITH_LIBXML=false
env:
  - WITH_LIBXML=true
  - WITH_LIBXML=false
before_script: |
  if [ "$WITH_LIBXML" == "false" ]; then
    sudo apt-get remove libxml2-dev
  fi
sudo: required
cache: bundler
